name: Continuous Integration

on:
  pull_request:
    branches: [main, development, testing]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install backend dependencies
        working-directory: src/backend
        run: npm ci
        
      - name: Lint backend
        working-directory: src/backend
        run: npm run lint
        
      - name: Type check backend
        working-directory: src/backend
        run: npm run typecheck
        
      - name: Install frontend dependencies
        working-directory: src/web
        run: npm ci
        
      - name: Lint frontend
        working-directory: src/web
        run: npm run lint

  test-backend:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install backend dependencies
        working-directory: src/backend
        run: npm ci
        
      - name: Run backend tests
        working-directory: src/backend
        run: npm run test:coverage
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: src/backend/coverage

  test-frontend:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install frontend dependencies
        working-directory: src/web
        run: npm ci
        
      - name: Run frontend tests
        working-directory: src/web
        run: npm run test:coverage
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: src/web/coverage

  build:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install backend dependencies
        working-directory: src/backend
        run: npm ci
        
      - name: Build backend
        working-directory: src/backend
        run: npm run build
        
      - name: Install frontend dependencies
        working-directory: src/web
        run: npm ci
        
      - name: Build frontend
        working-directory: src/web
        run: npm run build
        env:
          ORGANIZATION_CONFIGURATION_TABLE_NAME: 'test-organization-config'
          NEXT_PUBLIC_API_BASE_URL: '/api'
          
      - name: Create build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: src/web/.next